// ============================================
// cricket.ts — All TypeScript interfaces for CricIQ
// Import these in any component to get type safety
// ============================================

// ---- Match types ----

// A single match from the /api/matches/upcoming endpoint
export interface Match {
  match_id: string;          // unique match identifier
  team1: string;             // home/batting team name
  team2: string;             // away/bowling team name
  format: 'T20' | 'ODI' | 'Test' | 'IPL' | 'T20I';  // match format
  venue: string;             // ground name
  date: string;              // ISO date string
  status: 'upcoming' | 'live' | 'completed';  // current match status
  live_score?: LiveScore;    // only present if status === 'live'
}

// Current score data for a live match
export interface LiveScore {
  batting_team: string;      // which team is currently batting
  bowling_team: string;      // which team is currently bowling
  current_score: number;     // runs scored so far
  wickets: number;           // wickets fallen
  overs: string;             // e.g. "14.3" means over 14, ball 3
  run_rate: number;          // current run rate (CRR)
  target?: number;           // target score (only in 2nd innings)
  required_run_rate?: number; // RRR to win (only in 2nd innings)
}

// ---- Ball event (from WebSocket) ----
export interface BallEvent {
  over: number;              // which over (0-indexed)
  ball: number;              // which ball in the over (1-6)
  runs_this_ball: number;    // runs scored off this ball
  is_wicket: boolean;        // did a wicket fall?
  total_runs: number;        // team total after this ball
  wickets: number;           // total wickets fallen after this ball
  win_probability: number;   // 0.0 to 1.0 — batting team win probability
  momentum: number;          // delta in win probability (positive = batting team gaining)
  commentary: string;        // commentary text for this ball
  ball_type: 'dot' | 'single' | 'two' | 'three' | 'four' | 'six' | 'wicket';
  is_ai_commentary: boolean; // true if generated by Groq, false if pre-written
}

// ---- Win Probability Prediction ----
export interface PredictionInput {
  batting_team: string;
  bowling_team: string;
  format: 'T20' | 'ODI' | 'Test';
  venue: string;
  target: number;            // target score
  current_score: number;
  wickets: number;
  overs: number;             // e.g. 14.3 as a float
  pitch_type: 'flat' | 'green' | 'dusty' | 'fast';
}

export interface PredictionResult {
  win_probability: number;        // 0.0 to 1.0
  batting_team: string;
  bowling_team: string;
  shap_features: ShapFeature[];   // top 5 SHAP contributions
  h2h_win_rate: number;           // historical head-to-head win % at this venue
  model_accuracy: number;         // model accuracy (e.g. 0.84)
}

// ---- SHAP feature explanation ----
export interface ShapFeature {
  name: string;        // human-readable feature name
  impact: number;      // SHAP value — positive boosts, negative hurts
  value: string;       // actual value of this feature (e.g. "7 wickets")
}

// ---- Rivalry stats ----
export interface RivalryStats {
  total_matches: number;
  team1_wins: number;
  team2_wins: number;
  win_percentage: { team1: number; team2: number };
  avg_first_innings_score: number;
  highest_chase: number;
  year_by_year: { year: number; team1_wins: number; team2_wins: number }[];
  top_performers: {
    name: string;
    team: string;
    avg: number;
    matches: number;
  }[];
  most_dramatic_match: {
    date: string;
    result: string;
    description: string;
  };
}

// ---- Fantasy XI ----
export interface FantasyPlayer {
  name: string;
  role: 'BAT' | 'BOWL' | 'AR' | 'WK';   // AR = all-rounder
  team: string;
  credits: number;            // Dream11-style credits (6.0 to 11.0)
  predicted_points: number;   // our model's points prediction
  reason: string;             // why this player was selected
  is_captain: boolean;
  is_vice_captain: boolean;
}

export interface FantasyXI {
  xi: FantasyPlayer[];
  captain: string;
  vice_captain: string;
  total_credits_used: number;
  predicted_total_points: number;
}
